---
- name: Checking if client certificate are exist
  ansible.windows.win_uri:
    url: "{{ bareos_fd.hashicorp_vault.address }}/v1/{{ item.client }}/data/hosts/{{ item.name }}/bareos-certs"
    headers:
      X-Vault-Token: "{{ bareos_fd.hashicorp_vault.token }}"
      Content-Type: "application/json"
  register: cnout
  failed_when: false
  loop: "{{ bareos_fd.hashicorp_vault.clients }}"

- name: Create list for status code
  ansible.builtin.set_fact:
    stat_list: "{{ stat_list | default([]) + [ { 'cname': item.item.name, 'status': item.status_code, 'client': item.item.client, 'role': item.item.role, 'ttl': item.item.ttl } ] }}"
  with_items: "{{ cnout.results }}"
  loop_control:
    label: 
      - "{{ item.item.name }}"
      - "{{ item.status_code }}"

- name: Generate client certificate's with Hashicorp Vault
  ansible.windows.win_uri:
    url: "{{ bareos_fd.hashicorp_vault.address }}/v1/{{ bareos_fd.hashicorp_vault.path }}/issue/{{ item.role }}"
    url_method: POST
    headers:
      X-Vault-Token: "{{ bareos_fd.hashicorp_vault.token }}"
      Content-Type: "application/json"
    return_content: yes
    body:
      common_name: "{{ item.cname }}"
      ttl: "{{ item.ttl }}"
  when: item.status == 404
  with_items: "{{ stat_list }}"
  register: output

- name: Create list for serial key
  ansible.builtin.set_fact:
    cert_list: "{{ cert_list | default([]) + [ { 'cname': item.item.cname, 'status': item.item.status, 'client': item.item.client, 'ttl': item.item.ttl, 'serial_number': item.json.data.serial_number, 'certificate': item.json.data.certificate, 'priv_key': item.json.data.private_key } ] }}"
  when: item.item.status == 404
  with_items: "{{ output.results }}"
  loop_control:
    label:
      - "{{ item.item.cname }}"

- name: Save client certificate to Bareos TLS directory (bareos_tls_path_win)
  ansible.windows.win_copy:
    content: "{{ item.certificate }}"
    dest: "{{ bareos_tls_path_win }}/{{ item.cname }}.crt"
  when: 
    - item is defined
    - item.status == 404
  with_items: "{{ cert_list }}"
  run_once: true
  loop_control:
    label: 
      - "{{ item.cname }}.crt"

- name: Save client private key to Bareos TLS directory (bareos_tls_path_win)
  ansible.windows.win_copy:
    content: "{{ item.priv_key }}"
    dest: "{{ bareos_tls_path_win }}/{{ item.cname }}.key"
  when: 
    - item is defined
    - item.status == 404
  with_items: "{{ cert_list }}"
  run_once: true
  loop_control:
    label: 
      - "{{ item.cname }}.key"

- name: Add client serial number to Hashicorp Vault
  ansible.windows.win_uri:
    url: "{{ bareos_fd.hashicorp_vault.address }}/v1/{{ item.client }}/data/hosts/{{ item.cname }}/bareos-certs"
    url_method: POST
    headers:
      X-Vault-Token: "{{ bareos_fd.hashicorp_vault.token }}"
      Content-Type: "application/json"
    body:
      data:
        cname: "{{ item.cname }}"
        serial_number: "{{ item.serial_number }}"
  when: 
    - item is defined
    - item.status == 404
  with_items: "{{ cert_list }}"
  loop_control:
    label: 
      - "{{ item.cname }}"
      - "{{ item.serial_number }}"
