---
- import_tasks: install.yml
  tags:
    - install_bareos_fd
    - install
    - bareos_fd

- import_tasks: director.yml
  when: bareos_fd.director is defined
  tags:
    - configure_bareos_fd
    - bareos_fd_director
    - bareos_fd

- import_tasks: client.yml
  when: bareos_fd.client is defined
  tags:
    - configure_bareos_fd
    - bareos_fd_client
    - bareos_fd

- import_tasks: hashicorp.yml
  when: bareos_fd.hashicorp_vault is defined
  tags:
    - configure_bareos_fd
    - bareos_fd_hashicorp
    - bareos_fd

- import_tasks: messages.yml
  when: bareos_fd.messages is defined
  tags:
    - configure_bareos_fd
    - bareos_fd_messages
    - bareos_fd

- import_tasks: client_dir.yml
  when: bareos_dir.client is defined
  tags:
    - configure_bareos_dir
    - bareos_dir_client
    - bareos_dir

- import_tasks: fileset_dir.yml
  when: bareos_dir.fileset is defined
  tags:
    - configure_bareos_dir
    - bareos_dir_fileset
    - bareos_dir
